### ISSUE TITLE
The Tooltip position display of the tray icon is abnormal

### ISSUE THREAD

**Issue by zhanghj-v587** [hardcodet/wpf-notifyicon#106]
When the mouse quickly swipes into and out of the tray icon, there is a probability that Tooltips will appear in the upper left corner of the screen，
Please help to see how to solve this bug.
Thansk.

**Comment by p-try** [comment]
MR https://github.com/hardcodet/wpf-notifyicon/pull/96 fixed this for me. Would be nice if it was merged.

**Comment by punker76** [comment]
Fixed with #96
