### ISSUE TITLE
Cannot show icon

### ISSUE THREAD

**Issue by ShannonZ** [hardcodet/wpf-notifyicon#17]
` MyNotifyIcon.ShowBalloonTip("Tips", "Contents", new System.Drawing.Icon("icon.ico"),true);`
Cannot show any built-in icon or customized icon.

Version：1.0.8 （latest version from nuget）
.Net Framework 4.7.2
Window 10

**Comment by johndcollins** [comment]
Same issue Windows 10 1909. Can;t display the Balloon Tip.
Also having another issue probably related. When trying to right-click on the TaskIcon I get the following in my debug window:
"Unhandled NotifyIcon message ID: 123"

**Comment by Lakritzator** [comment]
Are there any errors, or details that might help?
Without more details, I don't know how to reproduce this and it works fine with my setup.

Can you try this repository, and specify what doesn't work in the sample applications?
Or create a simple sample repository which demos the issue?

P.S.
To my knowledge the debug info message with the unhandled message should not cause an issue.
But we are handling this in the newer version which is not yet available.

**Comment by johndcollins** [comment]
@Lakritzator this was happening on a Windows 1909 which was upgraded from a previous windows version. Once I wiped the machine and installed a fresh copy of Windows 1909 it worked again. I don't have the environment any longer to be able to reproduce this.

**Comment by Lakritzator** [comment]
Closing it as it can't be reproduced.
