### ISSUE TITLE
Add ability to show popups not only near mouse cursor.

### ISSUE THREAD

**Issue by MaksymSlota** [hardcodet/wpf-notifyicon#25]
Tray menu popup have default placement near  #cursor.
And it is the only option!
Add additional property PopupPlacement to have more options for this.

**Comment by Lakritzator** [comment]
Yeah, maybe a good idea! You are welcome to write a pull-request for that.

**Comment by MaksymSlota** [comment]
I have a local branch with this feature.
Can't push it. Permission to your repo is denied for me(

**Comment by Lakritzator** [comment]
That is not how it works, you will need to make a fork (a "private" copy of this repository, where you have all rights) , create your changes and push them in there and than provide a pull request. If everybody would be able to push in someone else's repository, think of the chaos.

**Comment by punker76** [comment]
Solved by #32
