### ISSUE TITLE
When change dpi, the ContextMenu's position is wrong?

### ISSUE THREAD

**Issue by WangElsie** [hardcodet/wpf-notifyicon#26]
When change dpi, the ContextMenu's position is wrong?
Do you have any workaround?

**Comment by Lakritzator** [comment]
I'm working on a solution where it can handle DPI changes during runtime, but first need to have another pull-request merged,

The workaround could be to restart the application, can you check this works?

But even with the planned changes, you also need to make sure your application is DPI aware, is this already the case?

**Comment by Lakritzator** [comment]
Just updating the status, still waiting for someone to review my [pull request](https://github.com/hardcodet/wpf-notifyicon/pull/21) so I can continue with that code.

**Comment by Lakritzator** [comment]
I've merged the mentioned PR, which means I can work on this.

**Comment by Lakritzator** [comment]
Fix will be available in 1.0.9 or later, I'm not sure when it's available.
