### ISSUE TITLE
Permanently visible icon

### ISSUE THREAD

**Issue by bboyle1234** [hardcodet/wpf-notifyicon#28]
Is there a way to stop windows hiding the icon? 
I know "every app" thinks its icon should be permanently visible, haha, and I don't expect that permanently visible needs to be a feature of this library, I just want to know how to at least initialize my icon to stay visible and let the user hide it they want to.
Thanks in advance :)

**Comment by Lakritzator** [comment]
Even if there would be a way, it would involve changing the Windows registry, and doing things which are not supported by Microsoft and also conflicting any guidelines / policies.

Anyway, there is nothing in this library what helps you.

**Comment by bboyle1234** [comment]
I use this library, with thanks, for the app icon :) 
Just wondering how it could be done (including by modifying the registry if necessary -- it's not about what's "meant to be" or the "right thing" ... it's about doing what my users are asking for. (And as you know with general public, most don't know how to do it for themselves.)

**Comment by Lakritzator** [comment]
You might have some luck by using google to look for "systemtray icon registry" or "notification icon registry".
https://superuser.com/questions/318088/make-specific-tray-icon-always-show-for-all-profiles-in-windows-7

But it's against the "rules", by taking over the PC you will not make many users happy.
