### ISSUE TITLE
Global Hot Keys support

### ISSUE THREAD

**Issue by tildebox** [hardcodet/wpf-notifyicon#30]
WPF: Implementing Global Hot Keys
https://social.technet.microsoft.com/wiki/contents/articles/30568.wpf-implementing-global-hot-keys.aspx

It would be great, if the window is in system tray, I just click a Global Hot Key e.g. ALT + L and the window appears.

Is this maybe already possible?

Any links how I can achieve this with the latest version?

"but when the form gets hidden and minimized to the system tray windows is unable to send the event message to the forms handle"

Is there still a solution?

**Comment by Lakritzator** [comment]
This project only brings you the notification icon functionality, if you like to do something with a hotkey you need another project. Try [NHotkey](https://github.com/thomaslevesque/NHotkey) for that.
