### ISSUE TITLE
.Net Core 3.0 support

### ISSUE THREAD

**Issue by punker76** [hardcodet/wpf-notifyicon#4]
After using the new csproj format we can now build the assembly also for the new .Net Core 3.0 (Preview).

**Comment by Tyrrrz** [comment]
Is this planned? Are there any blockers? Do you guys need help?

**Comment by Lakritzator** [comment]
dotnet core 3.0 has just been released, and the build servers like AppVeyor and Azure DevOps are not yet updated, and make building it a bit hard.

So please give the project a bit of time, it will come when it comes.
You should be able to use the current version without much issues.

**Comment by Tyrrrz** [comment]
AppVeyor had been updated with new image yesterday :)

**Comment by punker76** [comment]
@Tyrrrz It'll come the next days.

**Comment by Lakritzator** [comment]
@punker76 I don't know what you did up to now, as you had the issue I didn't want to do anything.
But I tried it anyway, and noticed that there are some issues with the resx files when building with dotnet core. I got things working, but only by keeping the WindowsFormsSample running with .NET Framework and not with dotnet core.

Here is my branch: https://github.com/Lakritzator/wpf-notifyicon/tree/feature/dotnetcore3

But I also changed the directory / file structure, and added nuget packaging when the build runs.
The version of the assembly and nuget package is calculated via Nerdbank.GitVersioning
I also added a Azure-DevOps build file, which **should** build the package, the release is still a separate step.

If you don't have much yet and like it, let me know...

**Comment by csutorasa** [comment]
Is there any reason why the change from @Lakritzator is not merged and released?

**Comment by Tyrrrz** [comment]
Also curious about the state of this @hardcodet.
Would be happy to help if you need any.

**Comment by GreatFireWall** [comment]
Is it works well for .net core 3.x now 😃

**Comment by Lakritzator** [comment]
Current status, awaiting review of https://github.com/hardcodet/wpf-notifyicon/pull/21
