### ISSUE TITLE
ContextMenu not showing after sleep, RDC connection or resolution change

### ISSUE THREAD

**Issue by milos12345** [hardcodet/wpf-notifyicon#40]
Context menu on tray icon would be working as expected, and would stop showing after some of these events:
- Computer going to sleep and waking up
- Logging via Windows Remote Desktop
- Multi-Monitor positions changed or resolution changed
This was happening inconsistency but reported by multiple users

**Comment by Lakritzator** [comment]
Did you try this with version 1.1? The release notes are here: https://github.com/hardcodet/wpf-notifyicon/milestone/1
Please let us know if that version solves the issues you are having, the part with remote desktop is also a bit hard for me to test.

**Comment by milos12345** [comment]
I am sorry, I thought I have closed this one. It turned out to be a different library responsible and for some reason a style of the context menu was causing this, and the only place I used it was on notifyicon. So this works. Thanks

**Comment by Lakritzator** [comment]
Thanks for the feedback!
