### ISSUE TITLE
ContextMenuOpening is not firing

### ISSUE THREAD

**Issue by Symbai** [hardcodet/wpf-notifyicon#41]
WPF .NET5 Nuget Version 1.0.8, ContextMenuOpening event never fires when context menu opens. See example code below

```
<tb:TaskbarIcon.ContextMenu>
    <ContextMenu ContextMenuOpening="ContextMenu_ContextMenuOpening" />
</tb:TaskbarIcon.ContextMenu>
```

Workaround is listening to `PreviewTrayContextMenuOpen` on `tb:TaskbarIcon.ContextMenu`

**Comment by punker76** [comment]
This is by design in WPF.

- https://github.com/dotnet/wpf/issues/8879#issuecomment-1983641847
- https://learn.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.contextmenuopening?view=windowsdesktop-8.0
