### ISSUE TITLE
Many tray icons after closing the program

### ISSUE THREAD

**Issue by AlfanyS** [hardcodet/wpf-notifyicon#42]

**Comment by Lakritzator** [comment]
This issue doesn't have any information which helps us to help you.
Please describe the issue in more details!

Just to make sure:
* You need to dispose the notify icon before you exit the application
* If the application is killed from the outside, there is no way to prevent this issue.

**Comment by Lakritzator** [comment]
Closing due to the lack of follow up, once you have more information you can always create a new issue.
