### ISSUE TITLE
ContextMenu oversized on dpiawareness PerMonitor

### ISSUE THREAD

**Issue by poochie89** [hardcodet/wpf-notifyicon#51]
My Application need to be PerMonitor DPIaware, this can be done with a manifest setting.
[https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process](url)

Howewer by doing this, the ContextMenu assigned to the tray icon appears oversized. Any fix for this?

**Comment by Lakritzator** [comment]
Did you try this with version 1.1? The release notes are here: https://github.com/hardcodet/wpf-notifyicon/milestone/1

**Comment by poochie89** [comment]
fixed
