### ISSUE TITLE
License consideration?

### ISSUE THREAD

**Issue by trungnt2910** [hardcodet/wpf-notifyicon#56]
Hi, I love all your controls here.
However, your license, the CPOL, prevents the library from being used in many open source projects because of its restrictions on "illegal" and "immoral" usage.
Could you please re-release this package under another popular license out there, such as the LGPLv3 or the MIT license? This could help other projects a lot!
Anyway, I don't see much use of notify icons for misdeeds anyway.

Thanks.

**Comment by Lakritzator** [comment]
I'm not the license holder nor an expert on licenses, but from my point of view you should explain in a bit more details why this should be done?

Can you elaborate why CPOL prevents you to use the **library**? I'm not extremely sure about the implications of using the DLL in any project vs. using the source, I guess you still need to add the license to your project? I'm no lawyer...

I never looked at CPOL in details, but I guess you mean that line "_You agree not to use the Work for illegal, immoral or improper purposes, or on pages containing illegal, immoral or improper material._"

I know that this restriction is a limitation, and open source should be as "freedom of speech". Although I myself wouldn't like to see my projects be used to do harm.

Let's have a discussion...

**Comment by trungnt2910** [comment]
I intended to create another _library_ myself, and wanted to use _this library_ as a dependency to my own. My library is locked under the GPL, which is [incompatible](https://www.gnu.org/licenses/license-list.en.html#cpol) with your library, licensed under the CPOL.

Also, I cannot license my library under a permissive license (MIT license or similar ones), because, as my library depends on the CPOL-licensed library, it is "covered" by the license, and I therefore don't have the ability to give my end users the right "to deal in the Software without restriction".

**Comment by Lakritzator** [comment]
@trungnt2910 thanks for your fast feedback, I will talk to the project author and get his standpoint on the license.

@hardcodet I agree with the idea behind CPOL, but it does make the usability of this repo very limited. I didn't yet integrate it in Greenshot, but looking at the current facts, I think I also cannot do that. It's an old license, I would advice to go with a more permissive license. Looking at CPOL and what it more or less means, I would also advice to use MIT or also LGPLv3, as was mentioned by @trungnt2910.

**Comment by Lakritzator** [comment]
@punker76 I'd love to hear your view on this, so we can advise Philipp.

**Comment by hardcodet** [comment]
I'm fine altering the license if the CPOL impairs adoption. MIT would work for me 👍

**Comment by punker76** [comment]
@Lakritzator I‘m also fine with MIT or LGPLv3
