### ISSUE TITLE
Balloontip wont show

### ISSUE THREAD

**Issue by unitrix0** [hardcodet/wpf-notifyicon#61]
I have a working tray icon, with context menu and everything works fine so far. But if I try to show a balloon tip with `ShowBalloonTip` just nothing happens.

What might be my mistake?

**Comment by unitrix0** [comment]
Firgured it out.... Had the notifiaction center set to "Alarms only"

**Comment by Lakritzator** [comment]
Thanks for the feedback, I read it back then but forgot to close the issue... ;)
