### ISSUE TITLE
Does this support .NET 5.0? Application instantly closes on executing a command without exception or error

### ISSUE THREAD

**Issue by JordanAnthonyKing** [hardcodet/wpf-notifyicon#68]
Hi, I've been trying to use this library, I've duplicated the code in the Windowless Sample in my .NET 5.0 project, and although a tray icon is shown, and a menu can be accessed, the application will close without exception or error when attempting to execute any of the commands.

My project with is available at https://github.com/JordanAnthonyKing/KeyboardUsurper/tree/NotifyIconIssue

**Comment by Lakritzator** [comment]
Yes, 1.1.0 works fine with .NET 5.0 and your test project also works for me (after I fix it to work without a configuration)
I see a disable, if I click it, I see an enable in the menu.

**Comment by JordanAnthonyKing** [comment]
Thanks for the response, would you be able to share the fix you made?

**Comment by Erapchu** [comment]
@JordanAnthonyKing Hello, you need to set ShutdownMode="OnExplicitShutdown" in App.xaml

**Comment by Erapchu** [comment]
That behavior occurs because your application doesn't have any window on startup and default value is OnLastWindowClose. No windows creating during application start. Only popups on mouse over, when they are vanished, last "window" (popup) closed and your application will closing.
