### ISSUE TITLE
Windowless: Contextmenu buttons are at the wrong time disabled and enabled

### ISSUE THREAD

**Issue by Schmo1** [hardcodet/wpf-notifyicon#69]
When i want to show the MainWindow in the Windowless solution, i can only press the "Hide Window" button.
.

**Comment by punker76** [comment]
This is finally fixed now by de175bfef2747aab91d40702fc0261c847ff6766

**Comment by Schmo1** [comment]
> This is finally fixed now by [de175bf](https://github.com/hardcodet/wpf-notifyicon/commit/de175bfef2747aab91d40702fc0261c847ff6766)

Thanks
