### ISSUE TITLE
Context Menu getting shown when left clicking

### ISSUE THREAD

**Issue by ptdev** [hardcodet/wpf-notifyicon#77]
As requested, opening an issue for the code comment [made here](https://github.com/hardcodet/wpf-notifyicon/commit/ec2e870cc613e8b9a0a588508105ecd5c3c9b95d#r71966509)

Basically, as long as a context menu is set, left clicking the icon will always trigger it after the commit mentioned above.
Tested on Windows 11

Cheers.

**Comment by HavenDV** [comment]
From https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyicona#remarks
> If a user selects a notify icon with the mouse and activates it with the ENTER key, the Shell now sends the associated application an NIN_SELECT notification. Earlier versions send [WM_RBUTTONDOWN](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-rbuttondown) and [WM_RBUTTONUP](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-rbuttonup) messages.

I think more complex behavior needs to be implemented here. Prior to Windows Vista, this was a right click. And now it is logical that the user should be able to customize the behavior.
