### ISSUE TITLE
Opening Context Menu instantly closes again

### ISSUE THREAD

**Issue by svr333** [hardcodet/wpf-notifyicon#79]
I've created the TaskbarIcon as following (although styles have been added, but the issue remains even when I use an exact copy of this TaskbarIcon.

The issue is that whenever I open the Context Menu (Right click), it'll instantly close after being open for about half a second.
I have no idea what causes this issue and messing around with the Focusable property didn't change anything

```xaml
<tb:TaskbarIcon x:Key="TaskbarIcon"
                    IconSource="pack://application:,,,/AudioBand;component/audioband.ico"
                    ToolTipText="AudioBand"
                    DoubleClickCommand="{Binding OpenSettingsMenuCommand}">
        <tb:TaskbarIcon.ContextMenu>
            <ContextMenu>
                <MenuItem Header="Settings" Command="{Binding OpenSettingsMenuCommand}">
                    <MenuItem.Icon>
                        <TextBlock  FontFamily="Segoe MDL2 Assets" Text="&#xF8B0;" />
                    </MenuItem.Icon>
                </MenuItem>
                <Separator />
            </ContextMenu>
        </tb:TaskbarIcon.ContextMenu>
    </tb:TaskbarIcon>
```

**Comment by Lakritzator** [comment]
A context menu usually closes when there is a change of focus, so the first thing that comes to my mind is that you might want to look if another thing steals the focus?

**Comment by svr333** [comment]
Yeah I've considered this too but I don't remember setting focus anywhere specifically. I'll check again tomorrow though!
Are there any limitations to what can take the focus? Only something TrayIcon related? Or is it possible it happens in my app itself too?

**Comment by NPatch** [comment]
I'm hitting the same issue. Within VS, ShowContextMenu is firing twice.
Once it comes from firing WM_CONTEXTMENU and the other is coming from WM_RBUTTONUP, somehow. If I comment out the [WM_RBUTTONUP invoke](https://github.com/hardcodet/wpf-notifyicon/blob/develop/src/NotifyIconWpf/Interop/WindowMessageSink.cs#L293), or the [WM_CONTEXTMENU invoke](https://github.com/hardcodet/wpf-notifyicon/blob/develop/src/NotifyIconWpf/Interop/WindowMessageSink.cs#L258), it works properly.

**Comment by NPatch** [comment]
Actually scratch that. The issue probably lies in https://github.com/hardcodet/wpf-notifyicon/blob/develop/src/NotifyIconWpf/TaskbarIcon.cs#L453.

This is the reason why the WM_RBUTTONUP msg, triggered the ShowContextMenu function. Not sure if this is needed by some of the samples, but WM_CONTEXTMENU already covers for it.

**Comment by svr333** [comment]
Good find, I don't know if PR's are still actively being merged but you can try to PR the change?

**Comment by NPatch** [comment]
I guess I can. I'll look into it a bit more later to check if there's a sample which uses that else block. Not sure what it was intended to cover if at all.
