### ISSUE TITLE
ShowBalloonTip 不显示提示框

### ISSUE THREAD

**Issue by longzu** [hardcodet/wpf-notifyicon#82]
string title = "WPF NotifyIcon";
            string text = "This is a standard balloon";

            this.sysNotifyIcon.ShowBalloonTip(title, text, this.sysNotifyIcon.Icon, true);

**Comment by Lakritzator** [comment]
I'm not sure what you want to say with this issue?

**Comment by WilliamQue** [comment]
@longzu Checking whether your windows is under focus mode (专注助手), if it's , the pop window of  balloontip will be blocked by windows，and nothing would show.
