### ISSUE TITLE
CI/CD fails with Tag 'TaskbarIcon' not found in Namespace 'http://www.hardcodet.net/taskbar'

### ISSUE THREAD

**Issue by buhralex** [hardcodet/wpf-notifyicon#94]
I'm currently in the process of implementing CI/CD in my repo and ran into a strange issue.
Project compiles fine on my machine without errors.
But when I push it to my Git server the build fails and I get the following message:

`error MC3074: The tag 'TaskbarIcon' does not exist in XML namespace 'http://www.hardcodet.net/taskbar'. Line 20 Position 6.`

Can anyone guide me in the right direction with this? Is this a problem with my Server or is this related to the namespace?

**Comment by Lakritzator** [comment]
I'd guess that you didn't restore nuget packages?

I'd suggest you do exactly as you do with CI/CD but locally to track your issue, checkout and run (just a guess) dotnet build and see what it does and go from there.

I will not really be able to help much though, as is actually not an issue with this repository, but with your build process..
If we start helping with every issue when a build doesn't work, we will swamp in issues, so I will close this issue.

**Comment by buhralex** [comment]
Thank you very much! You’ve guided me in the correct direction! I totally understand.
