### ISSUE TITLE
UX discrepancy in latest Windows 11 22H2 Moment 2 (build 1343) with Tool Tip Text

### ISSUE THREAD

**Issue by AliveDevil** [hardcodet/wpf-notifyicon#95]
Actual behavior:
![image](https://user-images.githubusercontent.com/734738/220695607-03530fef-c954-4e48-88a6-626cfba73f60.png)

While it should look like:
![image](https://user-images.githubusercontent.com/734738/220695684-72dc5e9b-3a7b-404e-98eb-cadf65564e04.png)

The misbehaving application uses
```
<tb:TaskbarIcon ToolTipText="{x:Static local:Localization.AssemblyProduct}"
```
as static tool tip text, without any other properties set.

Going to investigate here and provide further comment.

**Comment by Lakritzator** [comment]
Isn't that the same as https://github.com/hardcodet/wpf-notifyicon/issues/65 ?

**Comment by AliveDevil** [comment]
Unfortunately, no.
In current Windows 22621.1265 this looks like:
![image](https://user-images.githubusercontent.com/734738/220766309-d75b6f71-d86e-4e38-8a05-7f729d721cba.png)

**Comment by AliveDevil** [comment]
So basically, the "current" general availability release works as expected - any tool tip text looks the same.

The issue came up with users on the current Windows 11 22H2 Release Preview channel (22621 build 1343) mentioning that _all other_ applications support Microsofts "refreshed" tray area, while this application fails back to pre Windows 11 era tool tips for whatever reason.

**Comment by AliveDevil** [comment]
The official Windows 7 notification icon sample works just fine.

https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/winui/shell/appshellintegration/NotificationIcon

**Comment by AliveDevil** [comment]
What a stupid solution that is.

![image](https://user-images.githubusercontent.com/734738/220871405-acf69282-1400-4c55-a635-780c37d6cd70.png)

Works now, though 🤷‍♂️
